[package]
name = "day-01"
version = "0.1.0"
edition = "2021"
documentation = "https://adventofcode.com/2021/day/1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
utils = { path = "../utils" }

